services:
  fshare:
    image: twigman/fshare
    container_name: fshare
    command: --config /data/config.json --api-key 123 --comment "initial key" --highly-trusted
    volumes:
      - ./data:/data
    ports:
      - "8182:8080"