name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT: ${{ github.event.repository.name }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: Run go vet
        run: go vet ./...

      - name: Tidy & check go.mod/go.sum (safe)
        run: |
          go mod tidy
          git diff --exit-code $(find . -maxdepth 1 -name "go.mod" -o -name "go.sum")

      - name: Run tests
        run: go test -v ./...

  build-test:
    runs-on: ubuntu-latest
    needs: test

    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: Build binary (dev)
        run: |
          mkdir -p dist
          output_name=${PROJECT}-${{ matrix.goos }}-${{ matrix.goarch }}
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/$output_name ./src

      - name: List built files
        run: ls -l dist/

