name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT: ${{ github.event.repository.name }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.2'

    - name: Run go vet
      run: go vet ./...

    - name: Tidy & check go.mod/go.sum (safe)
      run: |
        go mod tidy
        git diff --exit-code $(find . -maxdepth 1 -name "go.mod" -o -name "go.sum")

    - name: Run tests
      run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    needs: test

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.2'

    # test builds
    - name: Build binaries
      run: |
        mkdir -p dist
        output_name=${PROJECT}-${{ matrix.goos }}-${{ matrix.goarch }}
        if [ "${{ matrix.goos }}" == "windows" ]; then
          output_name="${output_name}.exe"
        fi
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/$output_name .

    - name: List built files
      run: ls -l dist/

    #- name: Upload build artifacts
    #  if: github.ref_type == 'tag' || github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: ${PROJECT}-${{ matrix.goos }}-${{ matrix.goarch }}
    #    path: dist/${PROJECT}-${{ matrix.goos }}-${{ matrix.goarch }}*