name: Go Vulnerability Check

on:
  schedule:
    - cron: '0 2 * * *'  # daily at 2:00 UTC
  workflow_dispatch:     # and manually

jobs:
  vuln:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck and check results
        run: |
          govulncheck ./... > vuln-report.txt
          echo "===== govulncheck output ====="
          cat vuln-report.txt

          # check patterns
          if grep -q "Known vulnerabilities" vuln-report.txt; then
            echo "::error title=Vulnerabilities Found::Check govulncheck output"
            exit 1
          else
            echo "✅ No known vulnerabilities found"
          fi

      - name: Upload report (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vuln-report
          path: vuln-report.txt